sudo: false
language: go
go:
- 1.7
- 1.8
- 1.9
- tip
install:
- go get github.com/gogo/protobuf/...
- go get github.com/golang/protobuf/...
- go get github.com/pkg/errors/...
- go get github.com/stretchr/testify/...
- go get golang.org/x/net/...
script:
- go install ./...
- go test -race ./...
